### ISSUE TITLE
예제의 discovery 절차를 추적한다.

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/oidc-provider#5]
디비를 초기화하지 않고 예제를 돌리면 OP(openid provider)에서 400 Bad Request 응답이 생긴다.
백엔드 채널로 진행되는 discovery 과정에 문제가 있는 것으로 보인다.

**Comment by phi4grv** [comment]
Log at RP(relying party):
```
Started POST "/providers" for 127.0.0.1 at 2016-01-20 18:09:45 +0900
Processing by ProvidersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+8owZCANWTCtVnZqnFn7nSxgvf6URaYksP+gehdMSlw=", "host"=>"op.dev", "commit"=>"Discover"}
======= [WebFinger] HTTP REQUEST STARTED =======
GET /.well-known/webfinger?resource=https%3A%2F%2Fop.dev&rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer HTTP/1.1^M
Host: op.dev^M
^M

--------------------------------------------------
Status: 200 OK^M
Content-Type: application/jrd+json; charset=utf-8^M
X-UA-Compatible: IE=Edge^M
ETag: "e6d234ff68012663c97a3626c9ccae27"^M
Cache-Control: max-age=0, private, must-revalidate^M
X-Request-Id: d3ad70bc2470a1f93e9523aa2d51c5eb^M
X-Runtime: 0.050175^M
Date: Wed, 20 Jan 2016 09:09:47 GMT^M
Connection: close^M
Content-Length: 0^M
^M
{"links":[{"rel":"http://openid.net/specs/connect/1.0/issuer","href":"http://op.dev"}],"subject":"https://op.dev"}
======= [WebFinger] HTTP REQUEST FINISHED =======
  ^[[1m^[[36mProvider Load (0.2ms)^[[0m  ^[[1mSELECT "providers".* FROM "providers" WHERE "providers"."issuer" = 'http://op.dev' LIMIT 1^[[0m
Redirected to http://op.dev/authorizations/new?client_id=c2cf2d0726e1ecf3d28afac9dd9f5bbc&nonce=e9c6733a710c0bb395df38b6a9f78567&redirect_uri=http%3A%2F%2Frp.dev%2Fproviders%2F3%2Fopen_id&response_type=code&scope=openid+profile+email+address&state=e9c6733a710c0bb395df38b6a9f78567
Completed 302 Found in 2050.2ms (ActiveRecord: 0.2ms)
```

Log at OP
```
Started GET "/.well-known/webfinger?resource=https%3A%2F%2Fop.dev&rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer" for 127.0.0.1 at 2016-01-20 18:09:47 +0900
Processing by DiscoveryController#show as */*
  Parameters: {"resource"=>"https://op.dev", "rel"=>"http://openid.net/specs/connect/1.0/issuer", "id"=>"webfinger"}
Completed 200 OK in 8.3ms (Views: 0.3ms | ActiveRecord: 0.0ms)

Started GET "/authorizations/new?client_id=c2cf2d0726e1ecf3d28afac9dd9f5bbc&nonce=e9c6733a710c0bb395df38b6a9f78567&redirect_uri=http%3A%2F%2Frp.dev%2Fproviders%2F3%2Fopen_id&response_type=code&scope=openid+profile+email+address&state=e9c6733a710c0bb395df38b6a9f78567" for 127.0.0.1 at 2016-01-20 18:09:47 +0900
Processing by AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"c2cf2d0726e1ecf3d28afac9dd9f5bbc", "nonce"=>"e9c6733a710c0bb395df38b6a9f78567", "redirect_uri"=>"http://rp.dev/providers/3/open_id", "response_type"=>"code", "scope"=>"openid profile email address", "state"=>"e9c6733a710c0bb395df38b6a9f78567"}
  ^[[1m^[[36mClient Load (0.5ms)^[[0m  ^[[1mSELECT "clients".* FROM "clients" WHERE "clients"."identifier" = 'c2cf2d0726e1ecf3d28afac9dd9f5bbc' LIMIT 1^[[0m
/Users/phi4grv/Projects/2016/parti/local/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rack-oauth2-1.2.1/lib/rack/oauth2/server/authorize/error.rb:82:in `error!'
/Users/phi4grv/Projects/2016/parti/local/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rack-oauth2-1.2.1/lib/rack/oauth2/server/authorize/error.rb:64:in `bad_request!'
/Users/phi4grv/Projects/2016/parti/oidc-provider/lib/authorization_endpoint.rb:8:in `block in initialize'
/Users/phi4grv/Projects/2016/parti/local/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rack-oauth2-1.2.1/lib/rack/oauth2/server/abstract/handler.rb:13:in `call'
/Users/phi4grv/Projects/2016/parti/local/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rack-oauth2-1.2.1/lib/rack/oauth2/server/abstract/handler.rb:13:in `call'
/Users/phi4grv/Projects/2016/parti/local/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rack-oauth2-1.2.1/lib/rack/oauth2/server/authorize/code.rb:9:in `call'
/Users/phi4grv/Projects/2016/parti/local/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rack-oauth2-1.2.1/lib/rack/oauth2/server/authorize.rb:7:in `call'
/Users/phi4grv/Projects/2016/parti/oidc-provider/lib/authorization_endpoint.rb:3:in `call'
/Users/phi4grv/Projects/2016/parti/oidc-provider/app/controllers/authorizations_controller.rb:20:in `call_authorization_endpoint'
/Users/phi4grv/Projects/2016/parti/oidc-provider/app/controllers/authorizations_controller.rb:9:in `new'
  Rendered authorizations/error.html.erb within layouts/application (1.6ms)
  Rendered layouts/_header.html.erb (0.7ms)
  Rendered layouts/_footer.html.erb (0.6ms)
Completed 400 Bad Request in 49.2ms (Views: 27.5ms | ActiveRecord: 2.7ms)
```

**Comment by phi4grv** [comment]
Log at OP when RP registers provider:
```
Started GET "/.well-known/openid-configuration" for 127.0.0.1 at 2016-01-21 00:16:17 +0900
Processing by DiscoveryController#show as */*
  Parameters: {"id"=>"openid-configuration"}
  Scope Load (0.1ms)  SELECT "scopes".* FROM "scopes" 
Completed 200 OK in 2.1ms (Views: 0.6ms | ActiveRecord: 0.1ms)

Started POST "/connect/client" for 127.0.0.1 at 2016-01-21 00:16:17 +0900
Processing by Connect::ClientsController#create as */*
  Parameters: {"application_type"=>"web", "client_name"=>"NOV RP", "subject_type"=>"pairwise", "redirect_uris"=>["http://www.example.com/providers/3/open_id"]}
   (0.0ms)  begin transaction
  Client Exists (0.1ms)  SELECT 1 AS one FROM "clients" WHERE "clients"."identifier" = '5b4bee13738a848bfb9295ef7293c886' LIMIT 1
  SQL (0.3ms)  INSERT INTO "clients" ("account_id", "created_at", "dynamic", "expires_at", "identifier", "jwks_uri", "name", "native", "ppid", "raw_registered_json", "redirect_uris", "secret", "sector_identifier", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["account_id", nil], ["created_at", Wed, 20 Jan 2016 15:16:17 UTC +00:00], ["dynamic", true], ["expires_at", Wed, 20 Jan 2016 16:16:17 UTC +00:00], ["identifier", "5b4bee13738a848bfb9295ef7293c886"], ["jwks_uri", nil], ["name", "NOV RP"], ["native", false], ["ppid", true], ["raw_registered_json", "{\"application_type\":\"web\",\"client_name\":\"NOV RP\",\"subject_type\":\"pairwise\",\"redirect_uris\":[\"http://www.example.com/providers/3/open_id\"]}"], ["redirect_uris", "[\"http://www.example.com/providers/3/open_id\"]"], ["secret", "7d412c24531f265ddc9c28fb9603b4b3e403277b3873c8c2a1458972e53e6435"], ["sector_identifier", "www.example.com"], ["updated_at", Wed, 20 Jan 2016 15:16:17 UTC +00:00]]
   (0.5ms)  commit transaction
Completed 200 OK in 5.1ms (Views: 0.3ms | ActiveRecord: 1.0ms)
```

**Comment by phi4grv** [comment]
RP 디비에 OP정보가 없을때만 OP에 클라이언트 등록을 한다.
디비의 정보가 싱크가 되지 않을 경우 400 Bad Request 응답이 나타난다.
RP 디비를 리셋하면 해결된다.

**Comment by phi4grv** [comment]
```
$ curl -is 'http://op.dev/.well-known/webfinger?resource=https%3A%2F%2Fop.dev&rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer'

HTTP/1.1 200 OK
Content-Type: application/jrd+json; charset=utf-8
X-UA-Compatible: IE=Edge
ETag: "e6d234ff68012663c97a3626c9ccae27"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: d3aa364496177b42775118c0310f8907
X-Runtime: 0.002790
Date: Fri, 22 Jan 2016 09:10:52 GMT
Connection: close

{"links":[{"rel":"http://openid.net/specs/connect/1.0/issuer","href":"http://op.dev"}],"subject":"https://op.dev"}
```
